packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  typescript: ^5
  convex: ^1.31.2
  better-auth: 1.4.9
  "@convex-dev/better-auth": ^0.10.9
  "@types/node": ^24.10.4
  "effect": "^3.19.14"
  "@effect/language-service": "^0.63.2"
  zod: ^4.1.13
